// <auto-generated />
using System;
using Asteria.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asteria.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240411190025_Vendas")]
    partial class Vendas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Asteria.Domain.Entities.Vendas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("Categoria");

                    b.Property<int>("CodigoCliente")
                        .HasColumnType("int")
                        .HasColumnName("CodigoCliente");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Data");

                    b.Property<double>("Faturamento")
                        .HasColumnType("double(10,2)")
                        .HasColumnName("Faturamento");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("Quantidade");

                    b.Property<string>("sku")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("sku");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Categoria" }, "CATEGORIA_INDEX");

                    b.HasIndex(new[] { "CodigoCliente" }, "CODIGO_CLIENTE_INDEX");

                    b.HasIndex(new[] { "Data" }, "DATA_INDEX");

                    b.HasIndex(new[] { "sku" }, "SKU_INDEX");

                    b.ToTable("Vendas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
